/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import java.awt.Color;

/**
 *
 * @author Agnar
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminL
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelAname = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        APwtf = new javax.swing.JPasswordField();
        AdminNameTF = new javax.swing.JTextField();
        ALoginBtn = new javax.swing.JButton();
        ACancelBtn = new javax.swing.JButton();
        ForgetLabel = new javax.swing.JLabel();
        NewULabel = new javax.swing.JLabel();
        Adminpanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CashierLlabel = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JLabel();
        MinBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelAname.setForeground(new java.awt.Color(255, 255, 255));
        LabelAname.setText("User ID :");
        jPanel1.add(LabelAname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, 30));

        LabelPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        LabelPassword.setText("Password:");
        jPanel1.add(LabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, 28));

        APwtf.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(APwtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 270, 28));

        AdminNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        AdminNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(AdminNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 270, 30));

        ALoginBtn.setBackground(new java.awt.Color(102, 255, 204));
        ALoginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ALoginBtn.setForeground(new java.awt.Color(0, 153, 0));
        ALoginBtn.setText("Login");
        ALoginBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        ALoginBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        ALoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALoginBtnActionPerformed(evt);
            }
        });
        ALoginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ALoginBtnKeyPressed(evt);
            }
        });
        jPanel1.add(ALoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 100, 40));

        ACancelBtn.setBackground(new java.awt.Color(102, 255, 204));
        ACancelBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ACancelBtn.setForeground(new java.awt.Color(255, 0, 0));
        ACancelBtn.setText("Cancel");
        ACancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ACancelBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        ACancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ACancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 100, 40));

        ForgetLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ForgetLabel.setForeground(new java.awt.Color(0, 51, 204));
        ForgetLabel.setText("Forget Password ?");
        ForgetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetLabelMouseClicked(evt);
            }
        });
        jPanel1.add(ForgetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, -1));

        NewULabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NewULabel.setForeground(new java.awt.Color(0, 0, 255));
        NewULabel.setText("Create New Account");
        NewULabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewULabelMouseClicked(evt);
            }
        });
        jPanel1.add(NewULabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 115, 22));

        Adminpanel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        Adminpanel.setForeground(new java.awt.Color(255, 0, 0));
        Adminpanel.setText("Admin Login");
        jPanel1.add(Adminpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 310, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CashierLlabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CashierLlabel.setForeground(new java.awt.Color(0, 0, 255));
        CashierLlabel.setText("Cashier login");
        CashierLlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CashierLlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(CashierLlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(CashierLlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 210, 90));

        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close 2.png"))); // NOI18N
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        jPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 30));

        MinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-2.png"))); // NOI18N
        MinBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBtnMouseClicked(evt);
            }
        });
        jPanel1.add(MinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8.jpg"))); // NOI18N
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminNameTFActionPerformed

    private void ALoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALoginBtnActionPerformed
        // TODO add your handling code here:
        LoginController.AdminLogin(AdminNameTF.getText(), APwtf.getText());
    }//GEN-LAST:event_ALoginBtnActionPerformed

    private void ALoginBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ALoginBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALoginBtnKeyPressed

    private void ACancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACancelBtnActionPerformed
        // TODO add your handling code here:
        CashierLogin log = new CashierLogin();
        log.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_ACancelBtnActionPerformed

    private void NewULabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewULabelMouseClicked
        AddAdmin add = new AddAdmin();
        add.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_NewULabelMouseClicked

    private void CashierLlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashierLlabelMouseClicked
        // TODO add your handling code here:
        CashierLogin log  = new CashierLogin();
        log.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_CashierLlabelMouseClicked

    private void ForgetLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetLabelMouseClicked
        // TODO add your handling code here:
        
        ResetPWAdmin addminpw = new ResetPWAdmin();
        addminpw.setVisible(true);
    }//GEN-LAST:event_ForgetLabelMouseClicked

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        // TODO add your handling code here:
        // ColorChange(CloseBtn, new Color(255,51,51));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        // TODO add your handling code here:
        //ColorChange(CloseBtn, new Color(0,51,255));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void MinBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddAdmin.ICONIFIED);
        /* if(this.getExtendedState()!= AddAdmin.MAXIMIZED_BOTH){
            this.setExtendedState(AddAdmin.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(AddAdmin.NORMAL);
        }*/
    }//GEN-LAST:event_MinBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACancelBtn;
    private javax.swing.JButton ALoginBtn;
    private javax.swing.JPasswordField APwtf;
    private javax.swing.JTextField AdminNameTF;
    private javax.swing.JLabel Adminpanel;
    private javax.swing.JLabel CashierLlabel;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JLabel ForgetLabel;
    private javax.swing.JLabel LabelAname;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel MinBtn;
    private javax.swing.JLabel NewULabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
